"""
Summary generator service.

Creates condensed summaries (конспект) from cleaned transcripts.
A summary is a navigation document for those who already watched/read the content.

v0.24+: Generates from CleanedTranscript (not Longread) using 3-component prompt architecture.
v0.42+: Added tokens_used, cost, and processing_time_sec metrics.
"""

import json
import logging
import time
from typing import Any

from app.config import Settings, load_prompt, get_model_config
from app.utils.json_utils import extract_json
from app.utils import calculate_cost
from app.models.schemas import (
    CleanedTranscript,
    PromptOverrides,
    Summary,
    TokensUsed,
    VideoMetadata,
)
from app.services.ai_clients import BaseAIClient

logger = logging.getLogger(__name__)
perf_logger = logging.getLogger("app.perf")

# Russian month names for date formatting
RUSSIAN_MONTHS = [
    "", "января", "февраля", "марта", "апреля", "мая", "июня",
    "июля", "августа", "сентября", "октября", "ноября", "декабря"
]

# Valid topic_area values for classification
VALID_TOPIC_AREAS = [
    "продажи", "спонсорство", "лидерство",
    "мотивация", "инструменты", "маркетинг-план"
]

# Valid access_level values
VALID_ACCESS_LEVELS = ["consultant", "leader", "personal"]

# Default max input chars (for truncation if needed)
DEFAULT_MAX_INPUT_CHARS = 50000


class SummaryGenerator:
    """
    Summary generation service.

    Creates a condensed summary (конспект) from cleaned transcript.
    The summary helps those who already watched/read the content to
    quickly recall key points.

    v0.24+: Uses 3-component prompt architecture (system + instructions + template).
    LLM generates topic_area, tags, and access_level.

    Example:
        async with ClaudeClient.from_settings(settings) as client:
            generator = SummaryGenerator(client, settings)
            summary = await generator.generate(cleaned_transcript, metadata)
            markdown = summary.to_markdown()
    """

    def __init__(
        self,
        ai_client: BaseAIClient,
        settings: Settings,
        prompt_overrides: PromptOverrides | None = None,
    ):
        """
        Initialize summary generator.

        Args:
            ai_client: AI client for LLM calls
            settings: Application settings
            prompt_overrides: Optional prompt file overrides (v0.32+)
        """
        self.ai_client = ai_client
        self.settings = settings

        # Load 3-component prompt architecture with optional overrides
        overrides = prompt_overrides or PromptOverrides()
        self.system_prompt = load_prompt("summary", overrides.system or "system", settings)
        self.instructions = load_prompt("summary", overrides.instructions or "instructions", settings)
        self.template = load_prompt("summary", overrides.template or "template", settings)

        # Get model-specific config
        model_config = get_model_config(settings.summarizer_model, settings)
        summary_config = model_config.get("summary", {})
        self.max_input_chars = summary_config.get(
            "max_input_chars", DEFAULT_MAX_INPUT_CHARS
        )

        logger.debug(f"SummaryGenerator config: max_input_chars={self.max_input_chars}")

    async def generate(
        self,
        cleaned_transcript: CleanedTranscript,
        metadata: VideoMetadata,
        slides_text: str | None = None,
    ) -> Summary:
        """
        Generate summary from cleaned transcript.

        Args:
            cleaned_transcript: Cleaned transcript text
            metadata: Video metadata
            slides_text: Optional extracted text from slides (v0.68+)

        Returns:
            Summary with essence, concepts, tools, quotes, insight, actions,
            topic_area, tags, access_level (all generated by LLM)
        """
        start_time = time.time()

        # Prepare transcript text with optional slides
        transcript_text = self._prepare_text(cleaned_transcript, slides_text)
        input_chars = len(transcript_text)

        logger.info(
            f"Generating summary from cleaned transcript: {input_chars} chars"
        )

        # Build prompt
        prompt = self._build_prompt(transcript_text, metadata)

        # v0.43+: Unified interface - all clients return (response, usage)
        response, usage = await self.ai_client.generate(
            prompt, model=self.settings.summarizer_model
        )
        input_tokens = usage.input_tokens
        output_tokens = usage.output_tokens

        # Parse response with 1 retry on empty result (v0.68+)
        summary_data = self._parse_response(response)

        if not summary_data:
            logger.warning("Empty summary from LLM, retrying once")
            response2, usage2 = await self.ai_client.generate(
                prompt, model=self.settings.summarizer_model
            )
            input_tokens += usage2.input_tokens
            output_tokens += usage2.output_tokens
            summary_data = self._parse_response(response2)
            if summary_data:
                logger.info("Retry succeeded, got valid summary")
            else:
                logger.error("Retry also returned empty summary")

        elapsed = time.time() - start_time

        # Calculate cost if we have token data (v0.42+)
        tokens_used = None
        cost = None
        if input_tokens > 0 or output_tokens > 0:
            tokens_used = TokensUsed(input=input_tokens, output=output_tokens)
            cost = calculate_cost(
                self.settings.summarizer_model,
                input_tokens,
                output_tokens,
            )

        # Validate and normalize classification
        topic_area = self._validate_topic_area(summary_data.get("topic_area", []))
        access_level = self._validate_access_level(summary_data.get("access_level"))

        summary = Summary(
            video_id=metadata.video_id,
            title=metadata.title,
            speaker=metadata.speaker,
            date=metadata.date,
            essence=summary_data.get("essence", ""),
            key_concepts=summary_data.get("key_concepts", []),
            practical_tools=summary_data.get("practical_tools", []),
            quotes=summary_data.get("quotes", []),
            insight=summary_data.get("insight", ""),
            actions=summary_data.get("actions", []),
            # LLM-generated classification
            topic_area=topic_area,
            tags=summary_data.get("tags", []),
            access_level=access_level,
            model_name=self.settings.summarizer_model,
            tokens_used=tokens_used,
            cost=cost,
            processing_time_sec=elapsed,
        )

        logger.info(
            f"Summary complete: {len(summary.key_concepts)} concepts, "
            f"{len(summary.quotes)} quotes, topic_area={topic_area}, {elapsed:.1f}s"
        )

        cost_str = f"cost=${cost:.4f} | " if cost else ""
        perf_logger.info(
            f"PERF | summary | "
            f"input_chars={input_chars} | "
            f"concepts={len(summary.key_concepts)} | "
            f"quotes={len(summary.quotes)} | "
            f"tokens={input_tokens}+{output_tokens} | "
            f"{cost_str}topic_area={','.join(topic_area)} | "
            f"time={elapsed:.1f}s"
        )

        return summary

    def _prepare_text(
        self,
        cleaned_transcript: CleanedTranscript,
        slides_text: str | None = None,
    ) -> str:
        """
        Prepare cleaned transcript text with optional slides for prompt.

        If the transcript is too large, truncate it intelligently.

        Args:
            cleaned_transcript: Cleaned transcript
            slides_text: Optional extracted text from slides (v0.68+)

        Returns:
            Text ready for prompt insertion
        """
        text = cleaned_transcript.text

        # Truncate if needed
        if len(text) > self.max_input_chars:
            logger.warning(
                f"Transcript too large ({len(text)} chars), "
                f"truncating to {self.max_input_chars}"
            )
            text = self._truncate_text(text, self.max_input_chars)

        # Append slides context (same pattern as longread_generator)
        if slides_text:
            logger.info(f"Added slides context: {len(slides_text)} chars")
            text = (
                f"{text}\n\n"
                "---\n\n"
                "## Дополнительная информация со слайдов презентации\n\n"
                f"{slides_text}"
            )

        return text

    def _truncate_text(self, text: str, max_chars: int) -> str:
        """
        Truncate text intelligently, preserving structure.

        Tries to cut at paragraph boundaries rather than mid-sentence.

        Args:
            text: Full text
            max_chars: Maximum characters

        Returns:
            Truncated text with indication that it was cut
        """
        if len(text) <= max_chars:
            return text

        # Find a good cut point (at a paragraph or sentence)
        cut_point = max_chars - 100  # Leave room for truncation notice

        # Try to find last paragraph break before cut point
        last_para = text.rfind("\n\n", 0, cut_point)
        if last_para > max_chars // 2:
            return text[:last_para] + "\n\n[... сокращено для обработки ...]"

        # Try to find last sentence break
        last_sentence = max(
            text.rfind(". ", 0, cut_point),
            text.rfind("! ", 0, cut_point),
            text.rfind("? ", 0, cut_point),
        )
        if last_sentence > max_chars // 2:
            return text[:last_sentence + 1] + "\n\n[... сокращено для обработки ...]"

        # Fall back to hard cut
        return text[:cut_point] + "...\n\n[... сокращено для обработки ...]"

    def _build_prompt(self, transcript_text: str, metadata: VideoMetadata) -> str:
        """
        Build summary prompt from 3 components.

        Args:
            transcript_text: Prepared transcript text
            metadata: Video metadata

        Returns:
            Complete prompt for LLM
        """
        date_formatted = f"{metadata.date.day} {RUSSIAN_MONTHS[metadata.date.month]} {metadata.date.year}"

        prompt_parts = [
            self.system_prompt,
            "",
            "---",
            "",
            self.instructions,
            "",
            "---",
            "",
            "## Задание",
            "",
            "Создай конспект по транскрипту выступления.",
            "",
            f"**Спикер:** {metadata.speaker}",
            f"**Тема:** {metadata.title}",
            f"**Дата:** {date_formatted}",
            f"**Событие:** {metadata.event_type}",
            "",
            "### Транскрипт",
            "",
            transcript_text,
            "",
            "### Формат ответа",
            "",
            self.template,
        ]

        return "\n".join(prompt_parts)

    def _parse_response(self, response: str) -> dict[str, Any]:
        """
        Parse LLM response into summary data.

        Args:
            response: Raw LLM response

        Returns:
            Dict with summary fields
        """
        json_str = extract_json(response, json_type="object")

        try:
            data = json.loads(json_str)
            if not isinstance(data, dict):
                logger.error(f"Expected dict, got {type(data).__name__}")
                return {}
            return data
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON: {e}")
            logger.debug(f"Response was: {response[:500]}...")
            return {}

    def _validate_topic_area(self, topic_area: Any) -> list[str]:
        """
        Validate and normalize topic_area.

        Args:
            topic_area: Raw value from LLM (string or list)

        Returns:
            List of valid topic areas
        """
        # Handle string input
        if isinstance(topic_area, str):
            topic_area = [topic_area]

        # Handle non-list input
        if not isinstance(topic_area, list):
            return ["мотивация"]  # Default

        # Filter to valid values only
        valid = [t for t in topic_area if t in VALID_TOPIC_AREAS]

        # Default if empty
        if not valid:
            return ["мотивация"]

        return valid

    def _validate_access_level(self, access_level: Any) -> str:
        """
        Validate and normalize access_level.

        Args:
            access_level: Raw value from LLM

        Returns:
            Valid access level string
        """
        if access_level in VALID_ACCESS_LEVELS:
            return access_level
        return "consultant"  # Default
